# Generated by Django 4.1.3 on 2022-11-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_text", models.TextField()),
                (
                    "Show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shows.show"
                    ),
                ),
            ],
        ),
    ]
