# Generated by Django 4.1.3 on 2022-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="Show",
        ),
        migrations.AddField(
            model_name="show",
            name="lines",
            field=models.ManyToManyField(to="shows.line"),
        ),
    ]
