# Generated by Django 4.1.3 on 2022-11-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_remove_line_show_show_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="spoken_by",
            field=models.CharField(
                choices=[
                    ("1", "Actor 1"),
                    ("2", "Actor 2"),
                    ("3", "Actor 3"),
                    ("4", "Actor 4"),
                    ("5", "Actor 5"),
                    ("6", "Actor 6"),
                    ("7", "Actor 7"),
                    ("s", "Speakers"),
                    ("n1", "Narator 1"),
                    ("n2", "Narator 2"),
                ],
                default="",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
