# Generated by Django 4.1.3 on 2022-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0003_line_spoken_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="spoken_by",
            field=models.CharField(
                choices=[
                    ("A1", "Actor 1"),
                    ("A2", "Actor 2"),
                    ("A3", "Actor 3"),
                    ("A4", "Actor 4"),
                    ("A5", "Actor 5"),
                    ("A6", "Actor 6"),
                    ("A7", "Actor 7"),
                    ("S", "Speakers"),
                    ("N1", "Narator 1"),
                    ("N2", "Narator 2"),
                ],
                max_length=200,
            ),
        ),
    ]
